### ISSUE TITLE
Implement reading improvements

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/webpub-viewer#6]
The following need to be improved:

* Scrolling and pagination settings
* Settings for font size and margins
* Determine whether the book is fully downloaded and available offline, and show this information to the user.
* Add instructions about pagination controls and adding the book to your home screen.
* Redesign the navigation header

**Comment by aslagle** [comment]
This is done except "Add instructions about pagination controls and adding the book to your home screen." I don't think we need pagination control instructions if we implement swiping, and I think we can hold off on the home screen thing for now since I'm still not sure if or when it would be useful.
